export const MESSAGE = 'message'
export const REJECT_VIDEO_INVITE = 'reject-video-invite'
export const END_VIDEO_CALL = 'end-video-call'
export const END_SESSION = 'end-session'
export const TYPING_INDICATOR = 'typing-indicator'
export const CONNECTION = 'connection'
